### ISSUE TITLE
update config to point to newer archive

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/tri-trophic-thematic-collection-network#1]
Hi @seltmann - could you please close this issue once you've updated the url in `globi.json` file pointing to the newer darwin core archive file? Thanks!

**Comment by seltmann** [comment]
done!

**Comment by jhpoelen** [comment]
Thanks for updating the link. It'll take a couple of days for the changes to appear in GloBI. Hoping to get the new data in before your iDigBio talk. . .
